- type: department
  id: Cargo
  description: department-Cargo-description
  color: "#b32104"
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist

- type: department
  id: Civilian
  description: nes-department-pomirs-description
  color: "#64798a"
  weight: -10
  roles:
  - Bartender
  - Borg
  - Botanist
  - Boxer
  - Chaplain
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Lawyer
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  - ServiceWorker

- type: department
  id: Command
  description: nes-department-administrartion-description
  color: "#262630"
  roles:
  - Captain
  - IAA # Corvax-IAA
  - CentralCommandOfficial
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  primary: false
  weight: 100

- type: department
  id: Engineering
  description: nes-department-engineering-description
  color: "#c95a18"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  description: nes-department-medical-description
  color: "#18b6c9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic

- type: department
  id: Security
  description: nes-department-security-description
  color: "#20315d"
  weight: 20
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Detective
  - Warden

- type: department
  id: Science
  description: nes-department-science-description
  color: "#d8d3d8"
  roles:
  - ResearchDirector
  - Scientist
  - ResearchAssistant

